;all includes
#Include <\checklist\generateIni>
#Include <\checklist\premNotOpen>
#Include <\checklist\problemDir>
#Include <\checklist\trythenDel>
#Include <\checklist\timers>
#Include <\checklist\log>
#Include <\checklist\close>
#Include <\checklist\getPath>
#Include <\checklist\haltChecklist>