;// this script will simply remove all adobe symlink folders generated by `CreateSymLink.ahk`
#Include adobeVers.ahk
SplitPath(A_LineFile,, &scptDir)
imgsrchPath := scptDir '\..\..\ImageSearch'

for k, v in adobeVers.maps {
    which := adobeVers.which[k]
    for name, verMap in v.OwnProps() {
        for k2, v2 in verMap {
            if DirExist(imgsrchPath "\" which "\" k2)
                DirDelete(imgsrchPath "\" which "\" k2)
        }
    }
}