;// this script will simply remove all adobe symlink folders generated by `CreateSymLink.ahk`
#Include adobeVers.ahk
imgsrchPath := A_ScriptDir '\..\..\..\Support Files\ImageSearch'

for k, v in adobeVers.maps {
    which := adobeVers.which[k]
    for k2, v2 in v {
        if DirExist(imgsrchPath "\" which "\" k2)
            DirDelete(imgsrchPath "\" which "\" k2)
    }
}